### ISSUE TITLE
Autoscale script expects FaNDOM executable in wrong(?) place

### ISSUE THREAD

**Issue by ebioman** [jluebeck/FaNDOM#2]
Hi
Thanks a lot for this great tools, really appreciate them. 
Little remark concerning independent run of autoscaling.
I followed your installation instructions and the `FaNDOM` itself is in my PATH and execution works well.
The autoscaling script expects though the executable in the place of execution and does not pick up path of FaNDOM executable up itself. The documented option to provide it's path seems obsolete

**Comment by siavashre** [comment]
Hi ebioman,

Great finding! Thank you so much for pointing this. I fixed it.

Sincerely,
Siavash
