### ISSUE TITLE
INDEL size

### ISSUE THREAD

**Issue by ebioman** [jluebeck/FaNDOM#9]
Hi, I came along something which I dont understand at all concerning the INDEL description.
According to the header we have 

```
#Header	Type	Chromosome	RefStartPos	RefEndPos	SupportsIds	SupportsCount	PredictedSize
```
And I would have expected the "PredictedSize" to be roughly the RefEndPos - RefStartPos with some differences due to the precision problem with optical reads.
This seems to be though not really the case and they can wildly differ.
Just here a few extreme examples:

```bash

insertion	18	8301419.0	8381604.0	6991955	1	5003.0 80185 75182
insertion	4	129810167.0	129891372.0	8217652	1	9864.0 81205 71341
deletion	3	94684460.0	94777372.0	4062961	1	2707.0 92912 90205
insertion	1	117610005.0	117706624.0	4063023	1	5573.0 96619 91046

```
Here I added 2 columns at the end which is end-start and the difference between the predicted size and that observation.
I chose here the most extreme but you can see that the size is wildly different and I have trouble understanding this.

**Comment by siavashre** [comment]
Hi ebioman,

Thank you so much for your question. It is a really good question. With OM data, we can detect where indel happened but the  exact location of the indel is not known as four labels are involved (two on either side). Indel can happen in any location between two labels on the reference. Hence, in indel results in ref start and end we report labels locations and predicted size is size of indel happened in this region. 
So, what we know is that a indel with length of predicted size is happened in the region between start and end position. 

Please let me know if there is any more question. 

Sincerely,
Siavash
